#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Leigod Accelerator: Dedicated line for gaming acceleration. Pay by the minute, pause anytime.
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+leigod-acc +jq
PKG_VERSION:=1
PKG_RELEASE:=6

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

