name: 🐞 提交遇到的问题
description: 报告与游戏加速器插件相关的问题
labels: [bug]
body:
  - type: input
    id: openwrt-repo
    attributes:
      label: "OpenWrt 源码"
      description: "请提供您使用的 OpenWrt 源码仓库的链接或版本信息。"
    validations:
      required: true

  - type: checkboxes
    id: leigodacc-manager
    attributes:
      label: "是否使用了 openwrt-leigodacc-manager 进行修正"
      description: "如果使用了 [openwrt-leigodacc-manager](https://github.com/miaoermua/openwrt-leigodacc-manager)，请勾选并提供操作了哪些内容。"
      options:
        - label: "是"
        - label: "否"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: "问题类型"
      description: "请选择问题类型。例如游戏 A 可以正常加速游戏 B 不行选择游戏规则，如插件 LuCI 问题选择 LuCI 插件"
      options:
        - "游戏规则"
        - "LuCI 插件"
        - "管理器"
        - "其他"
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: "问题描述"
      description: |
        请详细描述您遇到的问题，包括但不限于以下内容：
        1. **网络拓扑**：请提供您的网络大致拓扑结构（例如：OpenWrt设备、无线路由器、客户端设备的连接方式）。
        2. **其他插件启用情况**：请列出您当前启用的其他插件或服务，方便我们检查对 Leigod 的冲突。
        3. **错误日志**：如果有任何错误日志或系统日志，请一并提供。
        4. **复现步骤**：请详细描述问题的复现步骤，以便我们能够更好地理解和重现问题。
      placeholder: "请详细描述问题..."
    validations:
      required: true
